[package]
name = "firefox-launcher"
version = "0.1.3"
authors = ["susurri <susurrus.silent@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"

[dependencies]
procfs = { version = "0.15", default-features = false }
rust-ini = "0.18"
rustyline = "11.0"
x11rb = "0.11"
xdg = "2.4.1"
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"
libc = "0.2"
nix = "0.26"
strum = "0.24"
strum_macros = "0.24"
