[package]
name = "firefox-launcher"
version = "0.1.9"
authors = ["susurri <susurrus.silent@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
readme = "README.md"

[dependencies]
procfs = { version = "0.15", default-features = false }
rust-ini = "0.19"
rustyline = "12.0"
x11rb = "0.12"
xdg = "2.5.2"
serde = { version = "1.0.186", features = ["derive"] }
serde_json = "1.0.105"
libc = "0.2"
nix = "0.26"
strum = "0.25"
strum_macros = "0.25"
